FROM nginx:1.27-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY *.html ./
COPY robots.txt sitemap.xml ./
COPY admin ./admin
COPY assets ./assets
COPY img ./img
COPY data ./data

EXPOSE 80
